config/routes.rb
Demumembership::Application.routes.draw do
  
  comfy_route :cms_admin, :path => '/admin'

  get "welcome/index"

  
  get '/members/by_days_to_expiry/:number_of_days_until_expiry', to: 'members#upcoming_renewals', as: 'members_by_days_to_expiry'
  get '/members/online_signups', to:'members#online_signups', as: 'members_online_signups'
  get '/members/expire', to: 'members#expire', as: 'members_expire'
  get 'members/signup', to: 'members#signup', as: 'members_signup'
  post 'members/join', to: 'members#join', as: 'members_join'

  get 'gocardless/confirm'

  match '/signin',                   to: 'sessions#new',                via: 'get'
  match '/signout',                  to: 'sessions#destroy',            via: 'delete'

  get '/payments/create_dd_payments', to: 'payments#create_dd_payments', as: 'payments_create_dd_payments'
  post '/payments/handle_notification',  to: 'payments#handle_notification', as: 'payments_handle_notification'

  get '/payments/test_handle_notification',  to: 'payments#test_handle_notification', as: 'payments_test_handle_notification'

  resources :members do
    resources :entitlement_periods
    resources :payments, only: [:destroy]
    resources :go_cardless_payment_methods, only: [:new]
    get 'go_cardless_payment_methods/create'
  end
  resources :area_groups
  resources :sessions, only: [:new, :create, :destroy]

  

  comfy_route :cms, :path => '/', :sitemap => true
end

app/models/area_group.rb
class AreaGroup < ActiveRecord::Base
	has_many :members
	belongs_to :coordinator, :class_name => "Member", :foreign_key => "coordinator_id"

	validates :name, presence: true, length: {minimum: 3 }
  	validates :description, presence: true, length: {minimum: 5}
  	validates_inclusion_of :active, :in => [true, false]

  	def to_s
		name
	end
end

app/controllers/area_groups_controller.rb
class AreaGroupsController < ApplicationController

	before_action :signed_in_member
	before_action :area_group_admin,   only: [:edit, :update, :new, :create, :destroy]

	def new
		@area_group = AreaGroup.new()
		@people = @area_group.members.sort_by!{ |m| m.forename.downcase }
	end

	def create
		@area_group = AreaGroup.new(area_group_params)
		@people = @area_group.members.sort_by!{ |m| m.forename.downcase }
		@area_group.save

		if @area_group.errors.none?
			redirect_to @area_group, :flash => {:success => "Area group created"}
		else
			render 'new'
		end
	end

	def show
		@area_group = AreaGroup.find(params[:id])
	end

	def index
  		@area_groups = AreaGroup.all
	end

	def edit
		@area_group = AreaGroup.find(params[:id])
		@people = @area_group.members.sort_by!{ |m| m.forename.downcase }
	end

	def update
		@area_group = AreaGroup.find(params[:id])
		@area_group.update_attributes(area_group_params)
		@people = @area_group.members.sort_by!{ |m| m.forename.downcase }

		if @area_group.errors.none?
			redirect_to @area_group
		else
			render 'new'
		end
	end

	def destroy
		@area_group = AreaGroup.find(params[:id])
		@area_group.destroy
		redirect_to area_groups_path, :flash => {:success => "Area group removed"}
	end

	private
		def area_group_params
			params.require(:area_group).permit(:name, :description, :active, :coordinator_id)
		end

		def signed_in_member
      		redirect_to signin_url, :flash => {:danger => "Please sign in."} unless signed_in?
    	end

		def area_group_admin
    		redirect_to area_groups_path, :flash => {:danger => "You are not allowed to perform that operation"} unless area_group_admin?
    	end
end

app/helpers/area_groups_helper.rb
module AreaGroupsHelper
	def selected_coordinator_id(area_group)
		if area_group.coordinator.nil?
			return ''
		else
			return area_group.coordinator.id
		end
	end
end

app/views/area_groups/_form.html.erb
<%= form_for @area_group, :html => { :class => "form-horizontal", :role => "form" } do |f| %>
  <% if @area_group.errors.any? %>
  <div id="errorExplanation" class="alert alert-danger" style="padding-top: 0px;">
    <h3><%= pluralize(@area_group.errors.count, "error") %> prohibited this area group from being saved:</h3>
    <ul>
    <% @area_group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12 col-md-6">

      <div class="form-group">
        <%= f.label :name, class: "col-xs-3 control-label" %>
        <div class="col-xs-9"><%= f.text_field :name, class: "form-control", style: "max-width: 200px"  %></div>
      </div>

      <div class="form-group">
        <%= f.label :description, class: "col-xs-3 control-label" %>
        <div class="col-xs-9"><%= f.text_field :description, class: "form-control", style: "max-width: 200px"  %></div>
      </div>

      <div class="form-group">
        <%= f.label :active, class: "col-xs-3 control-label" %>
        <div class="col-xs-9"><%= f.check_box :active, class: "form-control" %></div>
      </div>

      <div class="form-group">
        <%= f.label :coordinator, class: "col-xs-3 control-label" %>
        <div class="col-xs-9">
          <%= f.collection_select :coordinator_id, @people, :id, :to_s, {:selected => selected_coordinator_id(@area_group), :prompt => "Nobody assigned", :include_blank => true}, {:class => "form-control", :style => "max-width: 200px"} %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-xs-offset-3 col-xs-9">
          <%= f.submit class: "btn btn-sm btn-primary" %>
        </div>
      </div>

    </div>
  </div>
  
<% end %>

app/views/area_groups/edit.html.erb
<h1>Editing Area Group</h1>
 
<%= render 'form' %>
 

app/views/area_groups/index.html.erb
<h1 class="col-xs-10">Area Groups</h1>

<% if area_group_admin? %>
  <%= link_to "Add New Area Group", new_area_group_path, class: "btn btn-primary pull-right, col-xs-2", style: "margin-top: 20px;"  %>
<% end %>

<table class="table table-condensed">
  <tr>
    <th>Number</th>
    <th>Name</th>
    <th>Description</th>
    <th>Co-ordinator</th>
    <th>Active</th>
    <th>Actions</th>
  </tr>

  <% @area_groups.each do |area_group| %>
    <tr>
      <td><%= area_group.id %></td>
      <td><%= area_group.name %></td>
      <td><%= area_group.description %></td>
      <td><%= area_group.coordinator %></td>
      <td><%= area_group.active %></td>
      <td>
        <%= link_to 'Show', area_group_path(area_group), class: "btn btn-xs btn-primary" %>
        <% if area_group_admin? %>
          <%= link_to 'Edit', edit_area_group_path(area_group), class: "btn btn-xs btn-default" %>
          <%= link_to 'Destroy', area_group_path(area_group), method: :delete, data: {confirm: 'Are you sure?' }, class: "btn btn-xs btn-default"  %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/area_groups/new.html.erb
<h1>New Area Group</h1>

<%= render 'form' %>

app/views/area_groups/show.html.erb
<h2>Area Group Details:</h2>
<p>
  <strong>Name:</strong>
  <%= @area_group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @area_group.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @area_group.active %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @area_group.coordinator %>
</p>

<%= link_to "Area Groups List", area_groups_path, class: "btn btn-sm btn-default"  %>

<% if area_group_admin? %>
  <%= link_to "Edit Area Group", edit_area_group_path(@area_group), class: "btn btn-sm btn-primary"  %>


  <h2>Members:</h2>

  <table class="table table-condensed">
    <tr>
      <th>Number</th>
      <th>Forename</th>
      <th>Surname</th>
    </tr>

    <% @area_group.members.each do |member| %>
      <tr>
     	  <td><%= member.membership_number %></td>
        <td><%= member.forename %></td>
        <td><%= member.surname %></td>
      </tr>
    <% end %>
  </table>

<% end %>