config/routes.rb
Demumembership::Application.routes.draw do
  
  comfy_route :cms_admin, :path => '/admin'

  get "welcome/index"

  
  get '/members/by_days_to_expiry/:number_of_days_until_expiry', to: 'members#upcoming_renewals', as: 'members_by_days_to_expiry'
  get '/members/online_signups', to:'members#online_signups', as: 'members_online_signups'
  get '/members/expire', to: 'members#expire', as: 'members_expire'
  get 'members/signup', to: 'members#signup', as: 'members_signup'
  post 'members/join', to: 'members#join', as: 'members_join'

  get 'gocardless/confirm'

  match '/signin',                   to: 'sessions#new',                via: 'get'
  match '/signout',                  to: 'sessions#destroy',            via: 'delete'

  get '/payments/create_dd_payments', to: 'payments#create_dd_payments', as: 'payments_create_dd_payments'
  post '/payments/handle_notification',  to: 'payments#handle_notification', as: 'payments_handle_notification'

  get '/payments/test_handle_notification',  to: 'payments#test_handle_notification', as: 'payments_test_handle_notification'

  resources :members do
    resources :entitlement_periods
    resources :payments, only: [:destroy]
    resources :go_cardless_payment_methods, only: [:new]
    get 'go_cardless_payment_methods/create'
  end
  resources :area_groups
  resources :sessions, only: [:new, :create, :destroy]

  

  comfy_route :cms, :path => '/', :sitemap => true
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="/">© Diesel and Electric Modellers United 2013</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", controller: "/welcome" %></li>
      <li><%= link_to "Members", members_path %></li>
      <li><%= link_to link_to "Area Groups", controller: "/area_groups" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">

        <a class="navbar-brand" href="/"> <%= image_tag "Logo_40.png" %></a>
        <%= link_to "demu", '/', id: "logo" %>

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <%= render 'layouts/menu' %>
    </div>
  </nav>
</header>

app/views/layouts/_member_alert.html.erb
<% if signed_in? %>
  <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><%= param_1 %> </strong><%= param_2 %>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<div class="navbar-collapse collapse" id="my-navbar">
  <ul class="nav navbar-nav pull-right">

    <!-- CMS Menus -->
    <% @cms_site = Comfy::Cms::Site.find_by_id('1') %>
    <% unless @cms_site.nil?  %>
      <% @cms_site.pages.root.children.published.each do |page| %>
        <% unless (page.label == 'Forum') || (page.label == 'Wiki') %>

          <% unless page.children_count == 0 %>
            <% puts page.to_yaml %>
            <li class="dropdown">
              <a href="<%= page.full_path %>" class="dropdown-toggle" data-toggle="dropdown"><%= page.label %> <strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <% page.children.published.each do |subpage| %>
                  <li><%= link_to subpage.label, subpage.full_path %></li>
                <% end %>
              </ul>
            </li>
          <% else %>
            <li><%= link_to page.label, page.full_path %></li>
          <% end %>

        <% end %>
      <% end %>
    <% end %>

    <!-- Forum and Wiki -->
    <% if signed_in? %>
      <li><%= link_to 'Forum', '/forum' %></li>
      <li><%= link_to 'Wiki', '/wiki' %></li>
    <% else %>
      <li><%= link_to 'Forum', '/about/forum' %></li>
      <li><%= link_to 'Wiki', '/about/wiki' %></li>
    <% end %>

    <!-- My Membership -->
    <% if signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Membership <strong class="caret"></strong></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'View My Membership', member_path(current_member) %></li>
          <li class="divider"></li>
          <li><%= link_to "Area Groups", controller: "/area_groups" %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", signout_path, method: "delete" %></li>
        </ul>
      </li>
    <% else %>
      <li class="dropdown" id="menuLogin">
        <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin">Login <strong class="caret"></strong></a>
        <div class="dropdown-menu" style="padding:15px;">
          <%= form_for(:session, url: sessions_path, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>

            <p><%= f.text_field :login, placeholder: "Username", class: "form-control" %></p>
            <p><%= f.password_field :password, placeholder: "Password", class: "form-control" %></p>
            <%= f.hidden_field :fromnav, :value => "fromnav" %>

            <%= f.submit "Login", class: "btn btn-primary" %>
          <% end %>

        </div>
        <li class="divider"></li>
        <li><%= link_to "Sign up", members_signup_path %></li>
      </li>
    <% end %>

    <!-- Admin Menu -->
    <% if member_admin? || area_group_admin? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <strong class="caret"></strong></a>
        <ul class="dropdown-menu">
          <li><%= link_to "View Members", members_path %></li>
          
          <% if member_admin? %>
            <li><%= link_to "Create Member", new_member_url() %></li>
            <li class="divider"></li>
            <li class="dropdown-header">Renewal Process</li>
            <li><%= link_to "View Upcoming Renewals", members_by_days_to_expiry_path('30') %></li>
            <li><%= link_to "View Online Signups", members_online_signups_path %></li>
            <li class="divider"></li>
            <li class="dropdown-header">Scheduled Jobs</li>
            <li><%= link_to "Expire Members", members_expire_path %></li>
            <li><%= link_to "Create DD Payments", payments_create_dd_payments_path %></li>
          <% end %>

          <% if area_group_admin? %>
            <li class="dropdown-header">Area Group Admin</li>
            <li><%= link_to "Area Groups", controller: "/area_groups" %></li>
          <% end %>
          
          <% if member_admin? %>
            <li class="divider"></li>
            <li class="dropdown-header">Content Management</li>
            <li><%= link_to "CMS", main_app.comfy_admin_cms_path %></li>
          <% end %>

        </ul>
      </li>
    <% end %>

  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>DEMU</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag comfy_cms_render_css_path(@cms_site.id, @cms_layout.identifier)  unless @cms_site.nil? %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  
</head>
<body>
	<%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" style="margin-top: 20px;"><%= value %></div>
    <% end %>
		<%= yield %>
    <%= render 'layouts/footer' %>
	</div>
  
</body>
</html>

app/views/layouts/full_width.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>DEMU</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag comfy_cms_render_css_path(@cms_site.id, @cms_layout.identifier) unless @cms_site.nil? %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
	<%= render 'layouts/header' %>

  <%= yield %>

  <div class="container">
    <%= render 'layouts/footer' %>
  </div>
  
</body>

</html>