config/routes.rb
Demumembership::Application.routes.draw do
  
  comfy_route :cms_admin, :path => '/admin'

  get "welcome/index"

  
  get '/members/by_days_to_expiry/:number_of_days_until_expiry', to: 'members#upcoming_renewals', as: 'members_by_days_to_expiry'
  get '/members/online_signups', to:'members#online_signups', as: 'members_online_signups'
  get '/members/expire', to: 'members#expire', as: 'members_expire'
  get 'members/signup', to: 'members#signup', as: 'members_signup'
  post 'members/join', to: 'members#join', as: 'members_join'

  get 'gocardless/confirm'

  match '/signin',                   to: 'sessions#new',                via: 'get'
  match '/signout',                  to: 'sessions#destroy',            via: 'delete'

  get '/payments/create_dd_payments', to: 'payments#create_dd_payments', as: 'payments_create_dd_payments'
  post '/payments/handle_notification',  to: 'payments#handle_notification', as: 'payments_handle_notification'

  get '/payments/test_handle_notification',  to: 'payments#test_handle_notification', as: 'payments_test_handle_notification'

  resources :members do
    resources :entitlement_periods
    resources :payments, only: [:destroy]
    resources :go_cardless_payment_methods, only: [:new]
    get 'go_cardless_payment_methods/create'
  end
  resources :area_groups
  resources :sessions, only: [:new, :create, :destroy]

  

  comfy_route :cms, :path => '/', :sitemap => true
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :entitlement_periods, dependent: :destroy
  has_many :payments, dependent: :destroy
  belongs_to :membership_status
  belongs_to :member_category
  belongs_to :source_channel
  belongs_to :area_group
  has_one :contact_details, dependent: :destroy, autosave: true
  has_one :forum_details, dependent: :destroy, autosave: true
  has_one :subscription, dependent: :destroy, autosave: true
  has_one :go_cardless_payment_method, dependent: :destroy, autosave: true, as: :payment_methodable
  
  validates :forename, presence: true, length: {minimum: 1 }
  validates :surname, presence: true, length: {minimum: 2}
  validates :member_category, presence: true
  validates :membership_number, presence: true, numericality: true, uniqueness: true
  validates :contact_details, presence: true

  validate :forum_details_presence_for_online_signup

  def find_latest_entitlement
    entitlement_periods.last unless entitlement_periods.nil?
  end

  def paid_up_to_date
    if find_latest_entitlement.nil?
      'none'
    else
      find_latest_entitlement.end_date.to_s()
    end
  end

  def to_s
    forename + " " + surname
  end

  def activate
    puts 'Activating member:' + id.to_s
    self.membership_status = MembershipStatus.find_by_status(MembershipStatus::LIVE)
    self.save
  end

  def expire
    puts 'Expiring member:' + id.to_s
    self.membership_status = MembershipStatus.find_by_status(MembershipStatus::EXPIRED)
    self.save
  end

  def member_admin?
    forum_details.role == Role.find_by_description(Role::MEMBER_ADMIN)
  end

  def area_group_admin?
    forum_details.role == Role.find_by_description(Role::AREA_GROUP_ADMIN)
  end

  def has_pending_payment
    pending = false
    for payment in payments
      pending_status = PaymentStatus.find_by_description(PaymentStatus::PENDING)
      if payment.payment_status == pending_status
        pending = true
      end
    end
    pending
  end

  def add_entitlement_period(payment)
    # Only add an entitlement period if the payment is not linked to one already
    if payment.payable.nil?
      puts "starting creating entitlement period"

      entitlementdata = {end_date: calculate_next_entitlement_period_end_date}
      entitlement_period = entitlement_periods.build(entitlementdata)
    
      entitlement_period.member = self
      entitlement_period.payment = payment

      puts "saving entitlement period"
      entitlement_period.save
      
      puts "finished creating entitlement period"

      puts entitlement_period.errors.to_yaml

      self.activate
      self.save
    else
      puts "An entitlement period already exists for this payment"
    end
  end


  def revoke_entitlement_period(payment)
    unless payment.payable.nil?
      payment.payable.destroy
    end
    puts "Entitlement period removed from payment with id: " + payment.id.to_s
    recalculate_status
  end

  def recalculate_status
    expire_member = true
    for entitlement in entitlement_periods
      expire_member = false if entitlement.end_date > Date.today
    end
    if expire_member
      expire
    else
      activate
    end
  end

  # Either works out the end date based on the current entitlement period or
  # adds a year to the current date
  def calculate_next_entitlement_period_end_date()
    latest_entitlement = find_latest_entitlement
    if latest_entitlement.nil?
      Date.new(Date.today.next_year.year, Date.today.next_month.month, 1)
    else
      latest_entitlement.end_date.next_year
    end
  end

  def forum_details_presence_for_online_signup
    puts "validating forum details presence. Membershipp status = " + membership_status.to_s
    if membership_status.to_s == MembershipStatus::NEW

      unless forum_details.forum_name.present? && forum_details.forum_password.present?
        puts "found error"
        errors.add("Login Details", "can't be empty")
      end
    end
  end
  
end

app/controllers/members_controller.rb
	class MembersController < ApplicationController

	before_action :signed_in_member,          only: [:index, :show, :edit, :update, :new, :create, :destroy, :upcoming_renewals, :online_signups, :expire, :generate_passwords]
	before_action :list,                      only: [:index]
	before_action :own_record_or_admin_view,  only: [:show]
	before_action :own_record_or_admin_edit,  only: [:edit, :update]
	before_action :manage,   	              only: [:new, :create, :destroy, :upcoming_renewals, :online_signups, :expire, :generate_passwords]

	def new
		@member = Member.new(:date_added => Date.today)
		@contact_details = ContactDetails.new
		@forum_details = ForumDetails.new
		@max_member_id = Member.maximum("membership_number")
	end

	def create
		puts "Start"

		@member = Member.new(member_params)
		@member.member_category = MemberCategory.find(member_params[:member_category_id])
		unless member_params[:area_group_id].to_s == ''
			@member.area_group = AreaGroup.find(member_params[:area_group_id])
		end
		unless member_params[:source_channel_id].to_s == ''
			@member.source_channel = SourceChannel.find(member_params[:source_channel_id])
		end
		@member.membership_status = MembershipStatus.find_by_status(MembershipStatus::LIVE)
		
		puts "Pre-Contact Details"	
		@contact_details = ContactDetails.new(contact_details_params)
		@member.contact_details = @contact_details

		@forum_details = ForumDetails.new(forum_details_params)
		unless forum_details_params[:forum_id].blank?
			@member.forum_details = @forum_details
		end

		#Just in case there are other validation errors and we have to return to the page
		@max_member_id = Member.maximum("membership_number")

		puts "Pre-Save"
		@member.save
		
		puts "Finished"

		if @member.errors.none?
			redirect_to @member, :flash => {:success => "Member created"}
		else
			render 'new'
		end
		
	end

	def show
		@member = Member.find(params[:id])
	end

	def index
		@members, @alphaParams = Member.all.alpha_paginate(params[:letter]){|member| member.surname}
	end

	def edit
		@member = Member.find(params[:id])
		@contact_details = @member.contact_details
		@forum_details = @member.forum_details
		if @forum_details.nil?
			@forum_details = ForumDetails.new
		end
		@max_member_id = Member.maximum("membership_number")
	end
	
	def update

  		@member = Member.find(params[:id])
  		@member.member_category = MemberCategory.find(member_params[:member_category_id]) if member_admin?
  		@member.area_group = AreaGroup.find(member_params[:area_group_id]) if member_admin?
  		unless member_params[:source_channel_id].to_s == ''
  			@member.source_channel = SourceChannel.find(member_params[:source_channel_id]) if member_admin?
  		end

  		@member.contact_details.update(contact_details_params)
  		
  		#If we have forum details
  		unless params[:forum_details].nil?
  			#And if they are not empty...
  			unless forum_details_params[:forum_id].blank?
	  			#Do we already have any details?
	  			if !@member.forum_details.nil?
	  				@member.forum_details.update_attributes(forum_details_params)
	  			else
	  				@member.build_forum_details(forum_details_params)	
	  			end
	  			@forum_details = @member.forum_details
	  		end
	  	end

  		@member.update(member_params)
  		@contact_details = @member.contact_details
  		
  		if @member.errors.none? and @member.contact_details.errors.none?
    		redirect_to @member
  		else
    		render 'edit'
  		end
	end

	def destroy
		@member = Member.find(params[:id])
		@member.destroy

		redirect_to members_path, :flash => {:success => "Member removed"}
	end

	# NON-STANDARD METHODS
	def upcoming_renewals
		@number_of_days_until_expiry = params[:number_of_days_until_expiry]
  		targetDate = Date.today + params[:number_of_days_until_expiry].to_i.day
  		entitlements_expiring = EntitlementPeriod.where("end_date < ?", targetDate)#.where("end_date > ?", Date.today)
  		
  		@members = []
  		for entitlement in entitlements_expiring
  			@members.push(entitlement.member) if entitlement.member.membership_status == MembershipStatus.find_by_status(MembershipStatus::LIVE)
  		end

	end

	def online_signups
		new_status = MembershipStatus.find_by_status(MembershipStatus::NEW)
		@members = Member.where("membership_status_id = ?", new_status)
	end

	def expire
		entitlements_expiring = EntitlementPeriod.where("end_date < ?", Date.today)
		members = []
		live_status = MembershipStatus.find_by_status(MembershipStatus::LIVE)

		for entitlement in entitlements_expiring
			@member = Member.find(entitlement.member.id)
			if @member.membership_status == live_status
				if entitlement == @member.find_latest_entitlement
  					members.push(@member)
	  				@member.expire
	  				
	  			end
  			end
  			
  		end
  		render 'expire', :locals => { :members => members}
  	end

  	def signup
  		@member = Member.new(:date_added => Date.today)
  		@member.forum_details = ForumDetails.new
		@contact_details = ContactDetails.new

  		render 'new_signup'
  	end

  	def join

		params[:member][:membership_number] = Member.maximum("membership_number") + 1
		params[:member][:date_added] = Date.today
		@member = Member.new(join_member_params)
		@member.member_category = MemberCategory.find(join_member_params[:member_category_id]) unless join_member_params[:member_category_id].nil?
		@member.source_channel = SourceChannel.find_by_channel(SourceChannel::ONLINE)
		@member.membership_status = MembershipStatus.find_by_status(MembershipStatus::NEW)
		@member.contact_details = ContactDetails.new(contact_details_params)
		@member.forum_details = ForumDetails.new(forum_details_params)
		@member.forum_details.forum_password = Digest::SHA1.hexdigest (@member.forum_details.forum_name.to_s + @member.forum_details.forum_password)
		#TODO: Create forum login at this point
		@member.save
		
		if @member.errors.none?
			sign_in @member
			#redirect_to @member, :flash => {:success => "Membership created"}
			case params[:payment_type]
			when 'dd'
				# Process Direct Debit Payment
				redirect_to new_member_go_cardless_payment_method_path(:member_id => @member.id)
			when 'pp'
				# Process Pay Pal Payment
				redirect_to @member, :flash => {:success => "Membership created - paypal payment to follow"}
			end
		else
			@contact_details = @member.contact_details
			render 'new_signup'
		end
  		
  	end

	private
		def member_params
			if member_admin?
				params.require(:member).permit(:membership_number, :forename, :surname, :date_of_birth, :notes, :signup_source, :member_category_id, :source_channel_id, :area_group_id, :membership_status_id)
			else
				params.require(:member).permit(:forename, :surname, :date_of_birth)
			end
		end

		def join_member_params
			params.require(:member).permit(:membership_number, :forename, :surname, :date_of_birth, :member_category_id, :date_added)
		end

		def contact_details_params
			params.require(:contact_details).permit(:address_line_1, :address_line_2, :address_line_3, :town, :county, :postcode, :country, :telephone, :email)
		end

		def forum_details_params
			params.require(:forum_details).permit(:forum_id, :forum_name, :forum_password, :remember_token)
		end

		def signed_in_member
      		redirect_to signin_url, :flash => {:danger => "Please sign in."} unless signed_in?
    	end

    	def own_record_or_admin_view
      		@member = Member.find(params[:id])
      		redirect_to member_url(@current_member), :flash => {:danger => "You are not allowed to perform that operation"} unless (current_member?(@member) || member_admin? || area_group_admin?)
    	end

    	def own_record_or_admin_edit
      		@member = Member.find(params[:id])
      		redirect_to member_url(@member), :flash => {:danger => "You are not allowed to perform that operation"}  unless (current_member?(@member) || member_admin?)
    	end

    	def list
    		redirect_to member_url(@current_member), :flash => {:danger => "You are not allowed to perform that operation"} unless (member_admin? || area_group_admin?)
    	end

    	def manage
    		redirect_to member_url(@member), :flash => {:danger => "You are not allowed to perform that operation"} unless member_admin?
    	end
	
end

app/helpers/members_helper.rb
module MembersHelper
	
	def state_label(state)
	  	case state.to_s
	    	when "complete"
	      		"success"
	    	when "pending"
	      		"warning"
	      	when "failed"
	      		"important"
	      	when "chargedback"
	      		"important"
	      	when "refunded"
	      		"info"
	    	else
	      		"default"
	    end
	end

	def membership_state_label(state)
	  	case state.to_s
	    	when "live"
	      		"success"
	    	when "expired"
	      		"warning"
	      	when "quit"
	      		"important"
	    	else
	      		"default"
	    end
	end

end

app/views/members/_payment_ruler.html.erb
</tr><tr>

app/views/members/_source_details.html.erb
<div class="row">
  <div class="col-xs-7">Sign-up Source Channel:</div>
  <div class="col-xs-5"><strong><%= @member.source_channel %></strong></div>
</div>
<div class="row">
  <div class="col-xs-7">Sign-up Source:</div>
  <div class="col-xs-5"><strong><%= @member.signup_source %></strong></div>
</div>

app/views/members/edit.html.erb
<h1>Editing Member</h1>
 
<%= render 'form' %>
 

app/views/members/expire.html.erb
<h1>Expired Members</h1>

<p>Expired <%= members.count %> members.</br>
The following members have been set to expired:</p>

<table>
  <tr>
    <th>Number</th>
    <th>Forename</th>
    <th>Surname</th>
    <th>Paid Up To</th>
    <th>Status</th>
  </tr>

  <% members.each do |member| %>
    <tr>
      <td><%= member.membership_number %></td>
      <td><%= member.forename %></td>
      <td><%= member.surname %></td>
      <td><%= member.paid_up_to_date %></td>
      <td><%= member.membership_status %></td>
      <td><%= link_to 'Show', member_path(member), class: "btn btn-small btn-primary"  %></td>
      <td><%= link_to 'Edit', edit_member_path(member),class: "btn btn-small"  %></td>
      <td><%= link_to 'Destroy', member_path(member), method: :delete, data: {confirm: 'Are you sure?' }, class: "btn btn-small" %></td>
    </tr>
  <% end %>
</table>

app/views/members/index.html.erb
<h1>Members</h1>

<%= link_to "Add New Member", new_member_path, class: "btn btn-lg btn-primary pull-right"  %>

<%= alphabetical_paginate @alphaParams %>

<div id="pagination_table">
<table class="table table-condensed">
  <tr>
    <th>Number</th>
    <th>Forename</th>
    <th>Surname</th>
    <th>State</th>
    <th>Paid Up To</th>
    <th>Subscription Type</th>
    <th>Area Group</th>
    <th>Actions</th>
  </tr>

  <% @members.each do |member| %>
    <tr>
      <td><%= member.membership_number %></td>
      <td><%= member.forename %></td>
      <td><%= member.surname %></td>
      <td><span class="label label-<%= membership_state_label(member.membership_status) %>"><%= member.membership_status %></span></td>
      <td><%= member.paid_up_to_date %></td>
      <td><%= member.subscription.subscription_renewal_type unless member.subscription.nil? %></td>
      <td><%= member.area_group %></td>
      <td>
        <%= link_to 'Show', member_path(member), class: "btn btn-xs btn-primary" %>
        <%= link_to 'Edit', edit_member_path(member),class: "btn btn-xs btn-default" %>
        <%= link_to 'Destroy', member_path(member), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-xs btn-default" %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

app/views/members/new_signup.erb
<h1>Join DEMU</h1>

<p>You can join DEMU online today by completing the application form shown below. Alternatively, you can download our application form and return it to us by post.
</p>
<p><strong>Joining online is the quickest way for us to process your membership and means that you will have almost immediate access to our forum and wiki.</br> (Subject to a brief check by the membership secretary).</strong>

<p>Your membership year will run from the 1st of the month following the date you joined. So, for example, if you join on 23rd September, your membership will renew on 1st October each year.</p>

<%= render 'signup_form' %>

app/views/members/online_signups.html.erb
<h1>Online Sign-Ups</h1>

<p>The following <%= @members.count %> members have signed up online. They should already have access to the website and forum.</p>
<p>Please process their application by sending them their welcome pack and first issue of Update. Once complete, mark them as processed. This will then set their member state to LIVE.</p>
<p>Exceptions: If they didn't complete the payment step, they will have no Paid Up To Date and no forum login. Please contact them and then process their application as an offline renewal.</p>

<table class="table table-condensed">
  <tr>
    <th>Number</th>
    <th>Forename</th>
    <th>Surname</th>
    <th>Paid Up To</th>
    <th>Area Group</th>
    <th>Actions</th>
  </tr>

  <% @members.each do |member| %>
    <tr>
      <td><%= member.membership_number %></td>
      <td><%= member.forename %></td>
      <td><%= member.surname %></td>
      <td><%= member.paid_up_to_date %></td>
      <td><%= member.area_group %></td>
      <td>
        <%= link_to 'Show', member_path(member), class: "btn btn-xs btn-primary"   %>
        <%= link_to 'Edit', edit_member_path(member), class: "btn btn-xs btn-default" %>
        <%= link_to 'Destroy', member_path(member), method: :delete, data: {confirm: 'Are you sure?' }, class: "btn btn-xs btn-default"   %></td>
    </tr>
  <% end %>
</table>

app/views/members/show.html.erb
<div class="row" style="margin-top: 20px;" >

  <div class="col-sm-4">
    <div class="well well-small" style="padding-top: 0px">
      <h2>
        <%= @member.forename %> <%= @member.surname %>
        <%= @member.membership_number %><br/>
      </h2>

      <div class="row">
        <div class="col-xs-6 col-md-6">Date Of Birth:</div>
        <div class="col-xs-6 col-md-6"><strong><%= @member.date_of_birth %></strong></div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-md-6">Date Added:</div>
        <div class="col-xs-6 col-md-6"><strong><%= @member.date_added %></strong></div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-md-6">Member Category:</div>
        <div class="col-xs-6 col-md-6"><strong><%= @member.member_category.description %></strong></div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-md-6">Membership Status:</div>
        <div class="col-xs-6 col-md-6"><span class="label label-<%= membership_state_label(@member.membership_status.status) %>"><%= @member.membership_status.status %></span></div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-md-6">Area Group:</div>
        <div class="col-xs-6 col-md-6"><strong><%= @member.area_group %></strong></div>
      </div>

      <% if member_admin? %>
        <div class="row">
          <div class="col-xs-6 col-md-6">Notes:</div>
          <div class="col-xs-6 col-md-6"><strong><%= @member.notes %></strong></div>
        </div>
      <% end %>

      <div class="row" style="padding-top: 20px">
        <div class="col-xs-6 col-md-6">
          <%= link_to "Edit Member Details", edit_member_path(@member), class: "btn btn-sm btn-primary"  %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Contact Details</h3>
      </div>
      <div class="panel-body">
        <%= render @member.contact_details %>
      </div>
    </div>
  </div>

  <div class="col-sm-4">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Forum Details</h3>
      </div>
      <div class="panel-body">
        <% if @member.forum_details.nil? %>
          No forum details registered
        <% else %>
          <%= render @member.forum_details %>
        <% end %>
      </div>
    </div>

    <% if member_admin? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Source Details</h3>
        </div>
        <div class="panel-body">
          <%= render "source_details" %>
        </div>
      </div>
    <% end %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Subscription Details</h3>
      </div>
      <div class="panel-body">
        <% if @member.subscription.nil? %>
          No subscription registered
        <% else %>
          <%= render @member.subscription %>
        <% end %>
      </div>
    </div>
    
  </div>


</div>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Payment History</h3>
    </div>
    <% if @member.payments.empty? %>
      <div class="panel-body">
        No payments registered
      </div>
    <% else %>
      <table class="table" >
        <tr>
          <th>Payment ID</th>
          <th>Payment Date</th>
          <th>Payment Type</th>
          <th>Payment Currency</th>
          <th>GoCardless Ref</th>
          <th>Payment Status</th>
          <th>Actions</th>
        </tr>
        <tr><%= render partial: @member.payments, spacer_template: "payment_ruler" %></tr>
      </table>
    <% end %>
  </div>



<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Membership Periods</h3>
      </div>
      <% if @member.entitlement_periods.empty? %>
        <div class="panel-body">
          No entitlement periods registered
        </div>
      <% else %>
        <table class="table" style="margin-bottom: 0px">
          <tr>
            <th>End Date</th>
            <th>Related Payment</th>
            <th>Actions</th>
          </tr>
          <tr><%= render partial: @member.entitlement_periods, spacer_template: "payment_ruler" %></tr>
        </table>
      <% end %>
      <div class="panel-body" style="padding-top: 0px">
        <% if member_admin? %>
          <%= link_to 'Add Membership Period and Payment', new_member_entitlement_period_path(:member_id => @member.id), class: "btn btn-sm btn-primary"  %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Go Cardless Payment Method</h3>
      </div>
      <div class="panel-body">
        <% if @member.go_cardless_payment_method.nil? %>
          <p>No payment method registered</p>
          <%= link_to 'Add Go Cardless Payment Method', new_member_go_cardless_payment_method_path(:member_id => @member.id), class: "btn btn-sm btn-primary"  %>
        <% else %>
          <%= render @member.go_cardless_payment_method %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/members/upcoming_renewals.html.erb
<h1>Upcoming Renewals</h1>

<p>The following <%= @members.count %> members entitlements will expire in <%= @number_of_days_until_expiry %> days time.</p>

<p><%= link_to "30 days", members_by_days_to_expiry_path('30'), class: "btn btn-primary" %>
<%= link_to "60 days", members_by_days_to_expiry_path('60'), class: "btn btn-primary"  %>
<%= link_to "90 days", members_by_days_to_expiry_path('90'), class: "btn btn-primary"  %></p>

<table class="table table-condensed">
  <tr>
    <th>Number</th>
    <th>Forename</th>
    <th>Surname</th>
    <th>Paid Up To</th>
    <th>Area Group</th>
    <th>Actions</th>
  </tr>

  <% @members.each do |member| %>
    <tr>
      <td><%= member.membership_number %></td>
      <td><%= member.forename %></td>
      <td><%= member.surname %></td>
      <td><%= member.paid_up_to_date %></td>
      <td><%= member.area_group %></td>
      <td>
        <%= link_to 'Show', member_path(member), class: "btn btn-xs btn-primary"   %>
        <%= link_to 'Edit', edit_member_path(member), class: "btn btn-xs btn-default" %>
        <%= link_to 'Destroy', member_path(member), method: :delete, data: {confirm: 'Are you sure?' }, class: "btn btn-xs btn-default"   %></td>
    </tr>
  <% end %>
</table>